######################################################################
# Automatically generated by qmake (3.0) ke tammikuuta 20 22:48:36 2016
######################################################################

TEMPLATE = app
TARGET = fileReadWrite
INCLUDEPATH += .

# Input
SOURCES += hungarian.cpp
