######################################################################
# Automatically generated by qmake (3.0) ke tammikuuta 20 22:29:54 2016
######################################################################

TEMPLATE = app
TARGET = version
INCLUDEPATH += .

# Input
SOURCES += version.cpp
