% clear all; close all
format long g;

fs = filesep;
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LE71420412003102ASN00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'L5142041_04120111003' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LT50230302011290PAC01' fs];
% pathtofiles = ['..' fs '..' fs 'images' fs 'Landsat' fs ...
%     'LC81430402013256LGN00' fs];
pathtofiles = ['..' fs '..' fs 'images' fs 'Landsat' fs ...
    'L71171057_05720000125' fs];
% pathtofiles = ['..' fs '..' fs 'images' fs 'test' fs ...
%     'LE71420412003102ASN00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat8' fs ...
%     'LC81710572013148LGN00' fs];
% pathtofiles = ['..' fs '..' fs 'images' fs 'Landsat' fs ...
%     'LE71460382014016SG100' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LT51440402009284KHC00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LT51410412009295KHC00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LT51420412011292KHC00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LE70370352014068EDC00' fs];
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'LC80370352014076LGN00' fs];
 
% pathtofiles = ['F:' fs 'my_files' fs 'studies' fs 'LUT' fs ...
%     'doctoral_studies' fs 'shadows' fs 'images' fs 'Landsat' fs ...
%     'L5144040_04020110118' fs];
% define rows and columns to define the region to read from images
%      -- rows --    -- cols --
% rc = {[1762, 4717], [1126, 5324]};
% rc = {[700; 1099], [700; 1099]};

is_lic = check_lic('distrib_computing_toolbox');

if is_lic
    if ~matlabpool('size')
        matlabpool open
    end
end

tic;
if exist('rc', 'var')
    [I, bands] = Landsat_main(pathtofiles, rc);
else
    [I, bands] = Landsat_main(pathtofiles);
end
t_elp = toc;

% if is_lic
%     if matlabpool('size')
%         matlabpool close
%     end
% end
