######################################################################
# Automatically generated by qmake (3.0) to tammikuuta 21 13:23:22 2016
######################################################################

TEMPLATE = app
TARGET = qlist
INCLUDEPATH += .

# Input
SOURCES += mlist.cpp
