######################################################################
# Automatically generated by qmake (3.0) to tammikuuta 21 13:29:30 2016
######################################################################

TEMPLATE = app
TARGET = filters
INCLUDEPATH += .

# Input
SOURCES += filters.cpp
