######################################################################
# Automatically generated by qmake (2.01a) ke tammikuuta 20 22:38:42 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simpleGUI.cpp
