######################################################################
# Automatically generated by qmake (3.0) to tammikuuta 21 13:45:42 2016
######################################################################

TEMPLATE = app
TARGET = qtime
INCLUDEPATH += .

# Input
SOURCES += local_time.cpp
