######################################################################
# Automatically generated by qmake (3.0) to tammikuuta 21 13:25:50 2016
######################################################################

TEMPLATE = app
TARGET = qdir
INCLUDEPATH += .

# Input
SOURCES += home_dir.cpp
